"""followers

Revision ID: 81404d42e97c
Revises: 7c0547268d9b
Create Date: 2023-07-13 07:36:05.290770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81404d42e97c'
down_revision = '7c0547268d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
